FashionForecast/FashionForecast-client

- .github/workflows/cicd.yml
- .gitignore
- README.md
- src/pages/Home/index.tsx
- src/service/weather.ts
- src/types/weather.ts
- 배포 환경에서 백엔드와 통신 코드 테스트
- cicd 파일 제거
- 프로젝트 루트 폴더에서 `.env` 파일을 생성해주세요.
- types 폴더 변경 사항
- 기존: `types 폴더` → `user 폴더`, `weather 폴더`
- 변경 : `types 폴더` → `user.ts` `weather.ts`
- 나중에 type이 많아졌을 때 폴더별로 구분하는 게 좋겠습니다. 아직까진 구분을 안해도 괜찮을 것 같아요!
close #8
> 배포 환경에서 백엔드와 통신 코드 테스트

- src/service/weather.ts
> 하드코딩으로 query string 을 통해 전달했던 날짜와 시간을 date 객체를 통해 현재 시간, 날짜로 변경
>
> 날씨 호출 기준 현재 시간으로 변경(#19)

- src/components/layout/RootLayout/index.tsx
- src/constants/localStorage/key.ts
- src/service/login.ts
- src/types/login.ts
게스트 로그인 구현
localstorage에 게스트 uuid가 없다면, 게스트 로그인 요청을 보내 uuid를 저장합니다.
close #28
> 게스트 로그인 구현

- src/components/icon/Hyphen/index.tsx
- src/pages/Home/components/TimeSelector.style.ts
- src/pages/Home/components/TimeSelector.tsx
- src/pages/Home/index.tsx
- src/service/weather.ts
- src/utils/formatToISOString.ts
- src/utils/time.tsx
> 
(1) 기본값- 시작시간: 현재 시간, 종료 시간: 현재 시간 + 8시간
(현재 시간보다 8시간 이후 시간이 오늘 23시 이후인 경우 오늘 23시로 세팅)
(2) 사용자가 TimeSelector에서 시간 선택 가능
(3) 사용자가 선택한 StartTime에 맞게 -EndTime 범위가 달라짐
StartTime: 현재시간 ~ 오늘 23시
EndTime: StartTime ~ 오늘 23시
> Todo: 스타일링이 아직 익숙치 않아서 그런지,, 화면을 축소했을 때가 대응이 안되어 있습니다 ㅠㅠ 아직 스타일은 완성 전입니다!
> Feature/#33 time selector 구현

- src/pages/Home/components/TimeSelector.tsx
- src/service/weather.ts
> endDateTime 오류 수정
> 시간 로직 수정
> TimeSelector 내일인 경우 모든 시간대 보여주도록 수정
> 시간 로직 리팩토링 필요
> Fix/#33 시간 오류 수정

- src/pages/Home/components/RecommendClothes.tsx
기타 옷차림 문구 수정
- 꼭 알아두세요! → 꼭 챙기세요!
>
> 기타 옷차림 문구 수정

- src/assets/clothesImage/clothesImage.ts
- src/components/icon/Check/index.tsx
- src/pages/Home/components/RecommendClothes.tsx
- src/pages/Home/components/TimeSelector.style.ts
- src/pages/Home/components/TimeSelector.tsx
- src/pages/Home/components/WeatherTimeLine.tsx
- src/styles/theme.ts
- 타임라인의 `오전 12시` → `오전 00시` 문구 수정
- 추천 옷차림의 대표 이미지가 나타나지 않는 오류 수정
- `CheckIcon` color prop 추가
>
> 버그 수정 및 변경 사항 반영

- src/components/GoBackButton/index.tsx
- src/pages/Feedback/index.tsx
- src/pages/Feedback/style.ts
- src/pages/Home/components/Header/index.tsx
- src/pages/Search/components/SearchHeader/index.tsx
- src/pages/Search/components/SearchHeader/style.ts
- src/routes.tsx
- src/styles/theme.ts
- 로그인 관련 로직 주석 처리
- 고객의 소리(feedback) 페이지 구현
고객의 소리는 UI만 구현되어 있어서 api 구현이 필요합니다
> 비회원 기능 배포를 위한 작업

- src/components/CustomMui/CustomButton.tsx
- src/components/NetworkError/index.tsx
- src/components/layout/RootLayout/components/A2hsSnackbar/index.tsx
- src/pages/Feedback/index.tsx
- src/pages/Feedback/style.ts
- src/pages/Home/components/Header/index.tsx
- src/pages/Home/components/RecommendClothes/index.tsx
- src/pages/Home/components/TimeSelector/index.tsx
- src/pages/Home/components/TimeSelector/style.ts
- src/pages/Home/index.tsx
- src/pages/NotFound/index.tsx
- 네트워크 오류 UI 구현
- NotFound 페이지 스타일 적용
시간 변경 시, 추천 옷차림이 변경되지 않는 오류를 추가로 수정했습니다.
> 네트워크 오류 처리 및 NotFound 페이지 스타일 적용

- src/pages/Home/components/RecommendClothes/index.tsx
- src/pages/Home/components/TimeSelector/index.tsx
추천 옷차림 query key를 추가하여 시간 변경 시, 추천 옷차림 요청이 발생하도록 수정
> 시간 변경 시, 추천 옷차림이 변하지 않는 오류 수정

- index.html
> google analytics 적용

- src/components/CustomMui/CustomButton.tsx
- src/components/CustomMui/CustomSnackbar.tsx
- src/components/layout/RootLayout/components/A2hsSnackbar/index.tsx
- src/components/layout/RootLayout/components/A2hsSnackbar/style.ts
- src/components/layout/RootLayout/index.tsx
- src/contexts/SnackbarProvider.tsx
- src/main.tsx
- src/pages/Feedback/index.tsx
- src/service/feedback.ts
- 고객의 소리 제출 api 적용
- snackbar provider 구현
> 고객의 소리 제출 api 적용

- src/components/CustomMui/CustomDialog.tsx
- src/components/CustomMui/CustomFormControlLabel.tsx
- src/components/CustomMui/CustomRadio.tsx
- src/pages/Home/components/TimeSelector/TimeCarousel/index.tsx
- src/pages/User/components/TabSection/Lookbook/index.tsx
- src/pages/User/components/TabSection/MySetting/MenuItem/index.tsx
- src/pages/User/components/TabSection/MySetting/MenuItem/style.ts
- src/pages/User/components/TabSection/MySetting/RegionSetMenu/index.tsx
- src/pages/User/components/TabSection/MySetting/ThicknessSetMenu/index.tsx
- src/pages/User/components/TabSection/MySetting/TimeSetMenu/UserTimeSelector/index.tsx
- src/pages/User/components/TabSection/MySetting/TimeSetMenu/UserTimeSelector/style.ts
- src/pages/User/components/TabSection/MySetting/TimeSetMenu/index.tsx
- src/pages/User/components/TabSection/MySetting/TimeSetMenu/style.ts
- src/pages/User/components/TabSection/MySetting/index.tsx
- src/pages/User/components/TabSection/MySetting/style.ts
https://github.com/user-attachments/assets/95744e97-e4ef-4e90-b394-b89a618e8916
>
> 내 설정의 모달 마크업

- src/components/UserAvatar/index.tsx
- src/components/layout/PrivateRouteLayout/index.tsx
- src/components/layout/RootLayout/index.tsx
- src/pages/Home/components/Header/index.tsx
- src/pages/LoginAuth/index.tsx
- src/pages/NotFound/index.tsx
- src/pages/User/index.tsx
- src/pages/UserGender/UserGenderHeader/index.tsx
- src/pages/UserGender/UserGenderHeader/style.ts
- src/pages/UserGender/index.tsx
- src/redux/slice/userSlice.ts
- src/redux/store.ts
- src/routes.tsx
- src/service/auth.ts
- src/types/user.ts
- src/utils/auth.ts
- 회원 조회
- 회원 조회 api 적용 
- user 전역 상태 구현
- 성별 설정 api 적용
- 로그인 유저만 접근 할 수 있는 privateRouteLayout 구현
>
> 회원 조회 및 성별 설정 api 적용

- src/components/layout/RootLayout/index.tsx
- src/pages/UserGender/UserGenderHeader/index.tsx
- 성별 미설정 시, 성별 설정 페이지 이동 로직 추가
- 성별 설정 페이지에서 메인 페이지(`/`)로 이동하는 링크 제거
>
> 성별 미설정 시, 성별 페이지 이동 로직 추가

- src/pages/Home/components/TimeSelector/TimeCarousel/index.tsx
- src/pages/Home/components/TimeSelector/index.tsx
- src/pages/Home/index.tsx
- src/pages/User/components/TabSection/MySetting/TimeSetMenu/UserTimeSelector/index.tsx
- src/pages/User/components/TabSection/MySetting/TimeSetMenu/index.tsx
- src/service/auth.ts
- src/types/user.ts
- src/utils/auth.ts
- TimeCarousel 드래그 UX 개선
- `4.3.2` 기본 시간 설정
- 드래그 UX 개선
https://github.com/user-attachments/assets/0517b2c4-f46e-457e-b3ac-958e5dc3fbe1
- 시간 설정
https://github.com/user-attachments/assets/56e84527-0f83-4176-a1b3-491dcc3e3195
> 회원 시간 설정 구현

- src/components/layout/RootLayout/index.tsx
- src/pages/Search/components/CurrentRegionButton/index.tsx
- src/pages/Search/components/Index/RegionItem/index.tsx
- src/pages/Search/components/RecentSearchList/index.tsx
- src/pages/Search/index.tsx
- src/pages/User/components/TabSection/MySetting/RegionSetMenu/index.tsx
- src/pages/User/components/TabSection/index.tsx
- src/pages/User/index.tsx
- src/service/auth.ts
- `4.3.1` 기본 위치 설정
- 현재 위치
- 직접 설정
- 설정 값에 따라 날씨 및 옷차림 조회
https://github.com/user-attachments/assets/ba3e94ed-4c74-4254-9fcf-7cb88ed7ee71
> 기본 위치 설정 구현

- src/pages/Home/components/ClothesSection/index.tsx
- src/pages/User/components/TabSection/MySetting/ThicknessSetMenu/index.tsx
- src/service/auth.ts
- `4.3.3` 기본 옷차림 두께 설정
- 옷차림 두께 설정
- 설정값에 따라 추천 옷차림 조회
https://github.com/user-attachments/assets/5e127b95-5e1c-4bcf-93ee-09a8366b0134
> 기본 옷차림 두께 설정 구현

- src/pages/User/components/TabSection/MySetting/LogoutMenu/index.tsx
- src/pages/User/components/TabSection/MySetting/index.tsx
- src/service/auth.ts
`4.3.5` 로그아웃 기능 구현
https://github.com/user-attachments/assets/ef02aea1-84ec-4b85-825c-1f473a8d405f
> 로그아웃 기능 구현

- src/pages/Home/components/ClothesSection/RecommendClothes/index.tsx
- src/pages/Home/components/ClothesSection/RecommendClothes/style.ts
- src/types/clothes.ts
> 추천 옷차림 응답 데이터 변경

- src/pages/Login/components/LoginFooter/index.tsx
- src/pages/Search/components/RecentSearchList/index.tsx
- src/pages/Search/index.tsx
- src/pages/UserLookbookCreate/components/Edit/Showcase/index.tsx
- src/service/search.ts
- 회원은 회원 uuid로 최근 검색어 조회 및 변경
- 이용약관 및 개인정보처리방침의 누락된 link 추가
>
close #137
> 회원의 최근 검색어 조회 및 변경

- src/components/layout/RootLayout/style.ts
- src/pages/Feedback/style.ts
- src/pages/Home/style.ts
- src/pages/Login/style.ts
- src/pages/NotFound/index.tsx
- src/pages/User/style.ts
- src/pages/UserGender/style.ts
- src/pages/UserLookbookCreate/components/Edit/ColorPalette/style.ts
- src/pages/UserLookbookCreate/style.ts
- 일부 모바일 브라우저에서 주소 표시줄에 의해 ui가 어색한 부분 수정
- dvh 적용 
| 전 | 후 |
| --- | --- | 
| ![KakaoTalk_20241027_192017209](https://github.com/user-attachments/assets/858e2a26-b0d8-46a6-b50b-3856d76d914d) | ![KakaoTalk_20241027_192017209_01](https://github.com/user-attachments/assets/73a4a7f6-38b8-449b-b631-99568b54ea9c) |
> dvh css 적용

- src/pages/Home/components/ClothesSection/index.tsx
- src/service/clothes.ts
다음 조건 일때, 옷차림 두께를 `적당하게`로 변경하여 조회되도록 수정
- 날씨 그룹 1(28도 이상)일 때 사용자 설정 값이 `시원하게`인 경우
- 날씨 그룹 8(5도 미만)일 때 사용자 설정 값이 `따뜻하게`인 경우
- #143
> 추천 옷차림 조회 오류 수정

- package.json
- src/pages/Home/components/ClothesSection/index.tsx
- src/service/clothes.ts
> 1.1.1 버전 배포

- src/components/layout/RootLayout/index.tsx
- src/hooks/useGeolocation.tsx
- src/pages/Search/components/CurrentRegionButton/index.tsx
- src/redux/slice/geolocationSlice.ts
- 위치 권한 alert창 제거 및 Dialog 창으로 변경
- 위치 권한을 사용할 수 없을 때, `현재 위치로 설정하기` 버튼을 누르면 Dialog 창이 나오도록 변경
https://github.com/user-attachments/assets/0ae54d6c-90e2-476f-b859-50529a9aaaa3
> 위치 권한 alert창 제거

- public/naver8027c6e3ba4acb2994ecb22f130066fb.html
> 네이버 사이트 소유 확인

- package.json
- public/naver8027c6e3ba4acb2994ecb22f130066fb.html
> 1.1.3 버전 배포

- src/components/ClothesIcon/ClothesIcon.tsx
- src/components/IconLoading/IconLoading.tsx
- src/components/icon/pcp/PcpIcon.tsx
- src/components/icon/pop/PopIcon.tsx
- src/components/icon/temperature/TemperatureIcon.tsx
- src/components/icon/weather/WeatherIcon.tsx
- src/layout/PageLoading/PageLoading.tsx
- src/layout/PageLoading/pageLoading.style.ts
- src/layout/RootLayout/RootLayout.tsx
- src/main.tsx
- src/routes.tsx
- lazy loading 적용
- routes
- 아이콘
- 개발 환경(강력 새로고침) 기준
| 개선 전 | 개선 후 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5209cea7-5093-476b-b3f6-6b6f60b31266) | ![image](https://github.com/user-attachments/assets/bc9516e7-7cf4-494b-a404-7a04e23c938a) |
>
> lazy loading 적용

- src/services/search.ts
- src/utils/fetch.ts
> 유효하지 않는 비회원 uuid 처리 로직 변경

- src/pages/Home/ClothesSection/ClothesSection.tsx
- src/pages/Home/ClothesSection/LookbookList/LookbookList.tsx
추천 옷차림 이미지 매칭 오류 수정
- 옷차림 두께 옵션 변경에 따른 날씨 그룹 조정 로직 추가
>
> 추천 옷차림 이미지 매칭 오류 수정

- src/widgets/clothes/ui/RecommendClothesList/RecommendClothesList.tsx
> 옷차림 추천 꼭 챙기세요 항목의 이미지 매칭 오류 수정

- .vscode/settings.json
- src/features/feedback/ui/Feedback/Feedback.style.ts
- src/features/feedback/ui/Feedback/Feedback.tsx
- src/pages/Feedback/ui/Page/FeedbackPage.style.ts
- src/pages/Feedback/ui/Page/FeedbackPage.tsx
> 피드백 페이지 디자인 변경

- src/app/layouts/BaseLayout.tsx
- src/pages/Home/ui/HomeHeader/HomeHeader.tsx
최초 접근 & 위치 권한 허용 시, GPS 위치로 지역 선택
>
> 선택된 기준 위치 로직 변경

- package.json
- src/pages/Home/ui/HomePage.tsx
- src/shared/lib/ga.ts
- src/shared/lib/index.ts
- src/shared/types/global.d.ts
- src/widgets/time/ui/TimeBottomSheet/TimeBottomSheet.tsx
> 1.2.2  버전 배포
